name: Accesibility for Argentinas Law
description: This is a free action to test your application for compliance with Argentina's law
author: Joaquin Pettinari
branding:
  icon: "paperclip"
  color: "white"

inputs:
  port:
    description: "The port number for the development server"
    required: false
    default: "3000"

runs:
  using: "node20"
  main: "dist/index.js"
