name: Pa11y
on:
  pull_request:
    branches:
      - main

jobs:
  pa11y:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Accesibility for Argentinas Law
        uses: ./
        with:
          port: 5173
